before_script:
  - psql -c 'create database manifesto_test;' -U postgres

env: NO_SIMPLECOV=true DATABASE_URL=postgres://postgres:@localhost/manifesto_test

language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  # - jruby-19mode # http://travis-ci.org/#!/dylanegan/manifesto/jobs/1525115
  # - rbx-19mode # http://travis-ci.org/#!/dylanegan/manifesto/jobs/1976984

script: bundle exec rake test --trace
